services:
  backend:
    environment:
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_NAME=${DB_NAME}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        - SPRING_SECURITY_USERNAME=${SPRING_SECURITY_USERNAME}
        - SPRING_SECURITY_PASSWORD=${SPRING_SECURITY_PASSWORD}
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: ${JAR_FILE}
    ports:
      - "8080:8080"