services:
  backend:
    environment:
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_NAME=${DB_NAME}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        - SPRING_SECURITY_USERNAME=${SPRING_SECURITY_USERNAME}
        - SPRING_SECURITY_PASSWORD=${SPRING_SECURITY_PASSWORD}
        - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
        - FAL_KEY=${FAL_KEY}
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - snapthumb-network
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    hostname: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - snapthumb-network
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    networks:
      - snapthumb-network
    restart: always

  graylog:
    image: graylog/graylog:5.0
    container_name: graylog
    environment:
      - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET}
      - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}
      - GRAYLOG_HTTP_EXTERNAL_URI=${GRAYLOG_HTTP_EXTERNAL_URI}
      - GRAYLOG_MONGODB_URI=${GRAYLOG_MONGODB_URI}
      - GRAYLOG_ROTATION_STRATEGY=size
      - GRAYLOG_ELASTICSEARCH_MAX_SIZE_PER_INDEX=536870912
      - GRAYLOG_ELASTICSEARCH_MAX_NUMBER_OF_INDICES=2
      - GRAYLOG_ELASTICSEARCH_INDEX_PREFIX=graylog-dev

    ports:
      - "9000:9000"  
      - "12201:12201/udp"  
    networks:
      - snapthumb-network
    restart: always
    depends_on:
      - mongodb
      - elasticsearch
      
networks:
  snapthumb-network:
    driver: bridge
volumes:
  mongodb_data: