name: Deploy PostgreSQL & pgAdmin on EC2

on:
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID_DEV_POSTGRES }}
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy PostgreSQL & pgAdmin via AWS SSM
        run: |
          aws ssm send-command \
            --instance-ids "${{ env.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "set -e",
              "echo \"🔄 Stopping and removing existing containers...\"",
              "docker stop postgres_db || true",
              "docker rm postgres_db || true",
              "docker stop pgadmin || true",
              "docker rm pgadmin || true",
              
              "echo \"🛑 Removing old images...\"",
              "docker rmi postgres:14.13 || true",
              "docker rmi dpage/pgadmin4 || true",
              
              "echo \"📥 Pulling latest images...\"",
              "docker pull postgres:14.13",
              "docker pull dpage/pgadmin4",
              
              "echo \"🔗 Creating network internal (if not exists)...\"",
              "docker network create internal || true",
              
              "echo \"🗄 Creating volume postgres_data (if not exists)...\"", 
              "docker volume inspect postgres_data >/dev/null 2>&1 || docker volume create --name=postgres_data",
              
              "echo \"🚀 Starting PostgreSQL...\"",
              "VOLUME_PATH=$(docker volume inspect --format '{{ .Mountpoint }}' postgres_data)",
              "docker run -d \
                --name postgres_db \
                --network internal \
                --restart always \
                -e POSTGRES_DB=${{ secrets.DB_NAME }} \
                -e POSTGRES_USER=${{ secrets.DB_USERNAME }} \
                -e POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }} \
                -p 5432:5432 \
                -v $VOLUME_PATH:/var/lib/postgresql/data \
                postgres:14.13",
              
              "echo \"🚀 Starting pgAdmin...\"",
              "docker run -d \
                --name pgadmin \
                --network internal \
                --restart always \
                -e PGADMIN_DEFAULT_EMAIL=${{ secrets.PGADMIN_DEFAULT_EMAIL }} \
                -e PGADMIN_DEFAULT_PASSWORD=${{ secrets.PGADMIN_DEFAULT_PASSWORD }} \
                -p 5050:5050 \
                dpage/pgadmin4",
              
              "echo \"✅ PostgreSQL & pgAdmin successfully restarted!\""
            ]' \
            --output text